s <- 'CAGGTGGTCTTGTCCTCGGGGAGATCAGATGAGGATCGGCACGCTTGGGGATAACGCTCATACTGGCTAGATTACCTACTATAAAGTCCCTGTGTGTCACTTGGATCATTCATCCATTATCGCTTCGAAGAACCGATCGCAGATCACGGTCGATTTGTGAGACCCGATATGGTGGATGGGTATGACCACCACGGATGTGACATCTTGATCTTCAGGCCTGGCTGCCCCCAGAGCAGTAAGCCGTCTGGCCGGATGTTCTACGGAATAGTATAGTGGGGAGTGTCTATAACAGCACTAACGATCCGGGTCTTCCGTAATGATACGCCTATGGCACCTAGGCACGTTGCGTGGCATAATTTCTTGGTGCGTATCCACTCGCAGCATCTACTATCACCTAGAGCTCGCATCGTAGCCCCACTAGCAGGTCTTGCGCGGATGTCTCATTCCTACTCTTGTGCTTGCCCGAAGCATTGTATTCGGAGCCTCCAGATCTTGAGAAGACTTGAACGGAGTACCGGTGGGTCGGCACCCGTGTAAATGAGTTTCTGATGATAGAACTGGAGCCTTCCGCTTCCTGCGAAAAAAAAAACTCTAGACTATTCCAACAGGTTGAGCAATTAAGAATAATGGTTAACATAGATGGGTTTGGTTGTAGCTCACCGTCAGATTAGCACTAGTGCAACGGGCCGTTATCTGCAACAATGACGTTGTTCCTGCGGCAGTGCAGATTAGGGCGCCAATGGCTGGGACGAGGACCGCGTTCGCGACCGAATCTGGGGAATCAGGCACGTAACAGTCGGGTGACTTATAGCACAAACGCTATTCAGTTATGAATCCCATCTTAAGTGATAGCAGTAGGACCTGACGCCTTGTTATTCCCTTGAGAATTCGGTTCCAATACGAAGATCG'
A =0
t=0
C=0
G=0
for (i in 1:nchar(s)) {
  if (substr(s,i,i) =='A') {
    A = A+1
  } else if (substr(s,i,i) == 'T') {
    t = t+1
  } else if (substr(s,i,i) == 'C') {
    C= C+1
  } else if (substr(s,i,i) =='G') {
    G=G+1
  }
}
print(A)
print(C)
print(G)
print(t)

# one liner
# strsplit with empty split turns a string into a vector of separate chars
# see ?strsplit
table(strsplit(s, split=""))
