---
title: "ALPN_NBLAST"
author: "Marina Gkantia"
date: "2025-10-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "ALPN_NBLAST"
author: "Marina Gkantia"
date: "2025-10-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load the libraries

```{r}
library(dplyr)
library(fafbseg)
library(nat.nblast)
source("../funs/aedes-dataset-funs.R")
choose_aedes()
```


# Retrieve Aedes metadata

```{r}
aedes=flytable_query("select * from aedes_main WHERE status NOT IN ('duplicate','fragment','tiny')")
```

#Filter for ALPNs
```{r}
aedes %>% 
  filter(class=="ALPN") ->aedes_alpns
```

# are there any duplicates?
```{r}
aedes_alpns %>% filter(duplicated(aedes_alpns$root_id))
```

#Read dotprops
```{r}
alpns_dps<-read_l2dp(aedes_alpns)
```

#Check the units for dps
```{r}
boundingbox(alpns_dps)
```

# add metadata 
```{r}
alpns_dps[,]=aedes_alpns
```

#Plot ALPNs based by side
```{r}
nclear3d()
  plot3d(alpns_dps, col=case_when(side=="R" ~'red' , 
                               side=="L" ~ "green"))
```


#Mirroring registration

```{r}
u="https://spelunker.cave-explorer.org/#!middleauth+https://global.daf-apis.com/nglstate/api/v1/4693107724517376"

aedes_mirror.um=aedes_mirroreg()
```

```{r}
alpns.mirror=xform(alpns_dps, reg = aedes_mirror.um, subset = alpns_dps[,'side']=='L')
nclear3d()
plot3d(alpns.mirror, col=side)
```


#Run the NBLAST
```{r}
aba=nblast_allbyall(alpns.mirror, .progress='text')
```

#Run hierarchical clustering
```{r}
aba.hc=nhclust(aba)
```

#add dendrogram columns 
```{r}
pnmeta=coconat::add_cluster_info(df = aedes_alpns, aba.hc, k=40)
```

#Plot the 
```{r}
pdf(file =  ("/Users/marinagkantia/Documents/GitHub/2025aedes/R/Marina/osn_nblast_dendrograms/pnhcm-201025.pdf"), 
        width = 80, 
        height = 10, 
        family = 'Courier')
    
    par(mar = c(5,3,1,0))
a<-plot(aba.hc, labels=glue::glue("{root_id}_{side}_{group}_{type}",
                                  .envir = pnmeta), 
         hang = -.01, 
         cex = 0.5,
         lwd = 0.6)

dev.off()

```