s <- 'GCTACTTGTCATATAGACAGTACGTGTGTTATGGTATAACCCTCGTGGGTGCTGAGTCCTCAGTCTGCTAACCAGGGAGCTTGCGACTCTCAACTTGCTTCCTTCAGCCAACGTGTGCTTTAATCTTTTAAATCGTTGCCGCTCAATTTATACCCACAGGAGTAACAACAATCGTCGCTAACGGTTCGCCCTCAAAGGATTATGACATGGGTCCACCGCGCGTAAAAATGAGCACGGCTCATATATTTCGAGGGTTCTTGCTCGCTATTAAACCTTGACACGTAGAAAAAAGGGCGAATCGAAAAAGATTTTGTGCCGACGCGTTCCGGGGCTCGTAATCAGGCCACCTATGGTAGGTAGGCGTATAAGCGCGGAGTCTGAGCCAATCATTAACAGCATTCCGGTTCCGGGACTTTTTATACTCTAAAGACCTAGTGCGTATCCCATGGAGTCGCTAGACGATACTACTGGGCCTTGTCGTGTTGAGGCTAGGCGGTACTTAATTAACGCTTGCCGAGCGCTAGGGTTACCGCACCGTTCCCGGGTGGTTCCGGTCACTTGGGATGTGGTGCTCGTGTTGTGATCGATGATATGGAATTCAAGTGTGAATGTATCCCAACTCAGCGTCGATCACAGTTTTTGAGGCATCCAACCTCCCCCAACAGTTGAATACTTACCTCGCCTAATTCTCCCGATATTCCATAGTGCCTCTATGAAATCGTACGCGTAATGTACGAGTTCTGGTGCTCTGGGCCTACAATCCTCGTTGTCTGTTATAGGACCATGCACCGAGTGAACCTAGGCACATCGGGAGATTTCTTGAACGGTCATGAATCGAAGGAACAAAGGTTTCCAGTAGCGTACTGTCATCGTGCCAAACGATTGCGACTGGTGCATTTGGATCACGAGATAAACGATTTTCCATGATATTCGATTGGG'
result = ''
for (i in 1:nchar(s)) {
  if (substr(s,i,i) == 'T') {
    result <- paste(result, 'U', sep ='')
  } else {
    result <- paste(result, substr(s,i,i), sep='')
  }
}
print(result)

# Or a quick way to do the same
result2=gsub("T","U", s, fixed = T)
stopifnot(result==result2)
